Add properties "nominalInterestRate" and "remainingTerms" to "existingLoans" model (NO)
open-broker/specification pull request #111
Opened 2022-04-11 12:07 UTC by ElenaKurganova

Updating model of PrivateUnsecuredLoanApplicationCreated event for Norway based on new requirements.

2022-04-19 09:40 UTC, pn requested changes
Please fix issues in schema and example.

2022-04-19 09:40 UTC, pn commented on no/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanApplicationCreated.yaml
> +            and 100% as `1.0`.
Incorrect format. Decreasing indentation here should help.

2022-04-19 09:40 UTC, pn commented on no/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanApplicationCreated.yaml
> +            The number of month-terms required to payback the loan.
Decrease indent.

2022-04-19 09:40 UTC, pn commented on no/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json
> +                    "nominalInterestRate": null,
`null` is not allowed by schema for this field. Since the field is optional it can be omitted here.

2022-04-19 09:40 UTC, pn commented on no/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json
> +                    "nominalInterestRate": 0.019,
`nominalInterestRate` is a sting, so this value should be `"0.019"`.

2022-04-19 09:40 UTC, pn commented on no/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json
> +                    "nominalInterestRate": 0.045,
Value should be a string.

2022-04-19 09:40 UTC, pn commented on no/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json
> +                    "nominalInterestRate": null,
`null` not allowed here.

2022-04-19 09:40 UTC, pn commented on no/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json
> +                    "remainingTerms": null,
`null` not allowed here by proposed specification.

2022-04-19 09:45 UTC, zinob commented
Changes seem in accordance with requirements. I concur with @pn s change requests.

2022-07-22 08:09 UTC, pn approved these changes
Thank you for the fixes 👍

2025-08-13 14:47 UTC, merged